# Generated by Django 5.2.18 on 2026-10-06 21:38

import config.uploads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10)),
                ('descripcion', models.TextField()),
                ('lugar', models.CharField(max_length=200)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('foto', models.ImageField(blank=True, upload_to=config.uploads.foto_path, validators=[config.uploads.validar_foto])),
                ('fecha_avistamiento', models.DateField()),
                ('estado', models.CharField(choices=[('reportado', 'Reportado'), ('verificado', 'Verificado'), ('descartado', 'Descartado')], default='reportado', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('animal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avistamiento', to='animales.animal')),
                ('reportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado', '-id'],
            },
        ),
    ]
