# Generated by Django 5.2.18 on 2026-10-06 21:36

import config.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('desconocido', 'Desconocido')], default='desconocido', max_length=12)),
                ('edad_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to=config.uploads.foto_path, validators=[config.uploads.validar_foto])),
                ('estado', models.CharField(choices=[('adoptable', 'Adoptable'), ('adoptado', 'Adoptado')], default='adoptable', max_length=10)),
                ('refugio', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado', '-id'],
            },
        ),
    ]
