# Generated by Django 5.2.17 on 2026-08-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gato',
            new_name='Michi',
        ),
    ]
