# Generated by Django 5.2.17 on 2026-09-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_rename_gato_michi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='michi',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='michis/'),
        ),
        migrations.AddField(
            model_name='michi',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='michis', to='registro.dueno'),
        ),
    ]
